### ISSUE TITLE
Incompatibility with IntelliJ 2020.3+

### ISSUE THREAD

**Issue by TheBoar73** [redfoos/logstash-intellij-plugin#17]

**Comment by sheepsong** [comment]
> Plugin 'logstash config support' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.5981.155

**Comment by retyui** [comment]
![image](https://user-images.githubusercontent.com/4661784/102326074-9a33f600-3f8c-11eb-83e6-03748beb2355.png)

**Comment by fibsifan** [comment]
Hi,

I have noticed that The current build is failing since Dec 5. I Have looked into it and saw that the Class LogstashLanguage is loaded from two different locations in different tests:

* build/classes/java/main-instrumented/com/github/redfoos/logstash/LogstashLanguage.class
* idea-sandbox/idea-2020.3/plugins-test/logstash-intellij-plugin/lib/logstash-intellij-plugin-0.62-2020.3.jar!/com/github/redfoos/logstash/LogstashLanguage.class

Whichever load is the second, triggers an exception in IntelliJs Language class, since they check whether a Language had been loaded before.

In the tagged version releasebuild_0.62 only the class from the build directory is loaded.

Hope this helps.

**Comment by fibsifan** [comment]
Here is what I did:

1. I set a breakpoint at the Constructor of `com.github.redfoos.logstash.LogstashLanguage`
2. I added Watches with the following expressions:
   * `com.github.redfoos.logstash.LogstashLanguage.class.getClassLoader()`
      * Found different classloaders are used when the breakpoint is hit during execution of LogstashLexerTest and CompletionTest
   * `com.github.redfoos.logstash.LogstashLanguage.class.getClassLoader().getResource("com/github/redfoos/logstash/LogstashLanguage.class").toString()`
      * Different Locations as mentioned before.
3. I looked at the Stacktrace when the Breakpoint hit.
   * For the LogstashLexerTest the instantiation of LogstashLanguage happened during the test execution
   * For the CompletionTest the instantiation of LogstashLanguage happened outside (i assume before) the actual execution of any test method.

Unfortunately I'm not familiar with JUnit3 nor the IntelliJ test framework. I hope that this still helps towards a quick fix.

**Comment by hwy1782** [comment]
I also meet the proplem

**Comment by edgonzales** [comment]
Same here

**Comment by fibsifan** [comment]
Hi @redfoos

I tried transforming the plugin to the documented directory-structure from https://plugins.jetbrains.com/docs/intellij/custom-language-support-tutorial.html (moving src/com to src/main/java, tests to src/test/java etc. and fixing paths in build.gradle and in the tests), The issue then still persists.

Do you think this could be a problem with the test-framework?

I searched the IntelliJ issue tracker for issues with the test framework but found nothing that looked as if it could be the reason for this problem. Would it be in your interest to report a bug there and see what happens?

**Comment by redfoos** [comment]
@fibsifan, Hello! Thank you for your work, could you please send PR? 

As for the tests, I cannot be sure that this is a problem with the test framework, but, unfortunately, I now have absolutely no time to deal with this, since I am in the process of defending my diploma, it is possible that afterwards I will definitely figure it out. If you have an idea of ​​what you can write to the bug tracker and it's not difficult for you, then I'll be glad!

**Comment by fibsifan** [comment]
For the switch to gradle default layout see #18 

Regarding the issue with the tests I should probably create an example project to try to reprotuce the error before reporting. Maybe I'll find some time on one of the upcoming weekends and try it.

**Comment by redfoos** [comment]
Guys, it's completely unclear for me why all tests does not work together. It is look like some kind of 'pollution' tests context and I've spent around a day to understand how to fix and I failed.

Now for create plugin release I disabled parser and lexer tests.
