### ISSUE TITLE
Not displaying the matching parenthesis

### ISSUE THREAD

**Issue by ShanChathusanda93** [redfoos/logstash-intellij-plugin#5]
I am using this filter in my IntelliJ Ultimate but it isn't match and display the matching parenthesis. I searched about the issue but no any references were found. It is grateful if you can provide me a solution for this.
Thanks.

**Comment by ShanChathusanda93** [comment]
Hi @redfoos,
I just installed the logstash intellij plugin to my intellijIDEA IDE. Could you please explain more about what you need here?
Thanks.

**Comment by redfoos** [comment]
@ShanChathusanda93, i need configuration example on which an error occurs. Or maybe problem with filetypes? This plugin considers that the logstash configurations are written in a file with the type .conf, if it is not, or you have another plugin configured on .conf, then nothing will work. To fix this problem use this instruction: https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html

**Comment by StarveTheEgo** [comment]
He probably means brackets:
![image](https://user-images.githubusercontent.com/23626158/68397348-1a7e0a00-0184-11ea-9e7e-f9a93e147eed.png)

**Comment by ShanChathusanda93** [comment]
Hi @redfoos,
Very sorry for the late reply. @StarveTheEgo yes, I mean this issue.
Regards.

**Comment by redfoos** [comment]
Hi @ShanChathusanda93, @StarveTheEgo, i don't know why but in your example plugin does not parse the syntax elements, i try to reproduce it and got this:
![logts](https://user-images.githubusercontent.com/30526160/68458642-595ba080-0214-11ea-816c-2a048c2be3f3.png)
as you can see everything detected correct and plugin highlighting syntax of configuration. This could be possible only if you have errors in configuration above or below of this example.
The folding feature does not supported in plugin now, but i can add it in the next release.

**Comment by StarveTheEgo** [comment]
Yea, now i righclicked on one of my ***.conf** files, opened **Associate with File Type** dialog and selected LogStash, so it started to work normally about syntax and braces detection.

First time i installed it, i tried to update filename pattern for Logstash file type in Settings, to make it work for all ***.conf** files, but It did not work for some reason. Probably because of some conflict with Smarty config files (tho, i removed *.conf pattern from Smarty file type)

Anyway, it works now, after i associated with file type like this
Thank you !

_And folding feature will be useful, yea_
